import { cookies } from "next/headers";
import { Open_Sans } from "next/font/google";
import Header from "~/components/header/Header";

import "~/assets/css/index.css";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const city = cookieStore.get("city");

  return (
    <html lang="ru">
      <body className="relative" style={openSans.style}>
        <Header cityCookie={city?.value || "Кострома"} />
        {children}
      </body>
    </html>
  );
}
